service: zerowastechecklist-email

custom:
  secrets: ${file(secrets-${opt:stage, self:provider.stage}.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    email: hannahstahl14@gmail.com
    domain: ${self:custom.secrets.domain}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  send:
    handler: handler.send
    events:
      - http:
          path: email/send
          method: post
          cors: true
